services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer_api
    ports:
      - "8000:8000"
    volumes:
      - ./analysis_output:/app/analysis_output
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: ["gunicorn", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "main:app"]
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer_worker
    volumes:
      - ./analysis_output:/app/analysis_output
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: ["celery", "-A", "celery_config.celery_app", "worker", "--loglevel=info", "-c", "1"]
    depends_on:
      - rabbitmq